### ISSUE TITLE
Project assumes tenant ID is a Guid

### ISSUE THREAD

**Issue by matvelloso** [OfficeDev/O365-ASPNETMVC-Start#17]
so if you use the tenant name instead you land into an error page that assumes you didn't fill the tenant ID which is not the case. The project could avoid making that assumption or be more specific about what it expects in there.

**Comment by MIchaelMainer** [comment]
@matvelloso 

Thank you for this feedback. 

This sample is intended to be used around the Connected Services experience which adds the tenant identifier. With that said, if I add the tenant name instead of the identifier, I reproduce the error. The user is signed in, they can't access the functionality since there is an expectation of the tenant id. I'm going to take a look at this and get back to you. Thank you for sharing this with us.

**Comment by MIchaelMainer** [comment]
@matvelloso 
Updated so that this sample can be used with the tenant name. 

@*
Note to anyone that uses this sample. If you use the tenantId and switch to using the tenantName after ADAL has cached the token, the sample won't work until you clear the token cache.
