### ISSUE TITLE
AdalException	

### ISSUE THREAD

**Issue by bhallaheemanshu** [OfficeDev/O365-ASPNETMVC-Start#43]
Oops you've reached an error!
We weren't able to process the action you requested. This was caused by an exception in the below table:

Cause	
AdalException	This exception is thrown when either you have a stale O365 access token that can cause authentication errors, or you attempted to access a resource that you don't have permissions to access.

WHENEVER I OPEN www.manage.windowsazure.com i get **NO SUBSCRIPTION FOUND**

![rrrrrr](https://cloud.githubusercontent.com/assets/7411405/18003662/cb5d1d64-6bac-11e6-82d8-c460a7da37ae.PNG)

**Comment by DianeD** [comment]
Hi @bhallaheemanshu 
Did you associate the Azure/O365 directories? If so, you need to sign into the portal using your Live ID. If you try to log in with your O365 credentials, you'll get "No subscriptions found".

For the other error, please check your permissions described in the readme:
(Calendar) – Read and write to your calendars (ReadWrite)
(Contacts) – Read and write to your contacts (ReadWrite)
(Mail) - Send mail as you (Send), Read and write to your mail (ReadWrite)
(Files) - Read and write to your files (Write)
(Users and Groups) – Sign you in and read your profile (Read)

If they are correct, can you please try this?
i.	In Visual Studio, right-click your project and select Properties to open the project properties.
ii.	Click Web in the left navigation.
iii.	Under Start Action choose Specific Page and enter Account/SignOut.

**Comment by bhallaheemanshu** [comment]
@DianeD  ok Can i log in using outlook account i am having that .  i will try with that and for permissions while adding connected services i have given all permission as you specified

**Comment by bhallaheemanshu** [comment]
@DianeD  Just for info please let me know . Do I need to Pay somethinig to use any of the API provided in this repo

**Comment by jamescro** [comment]
I've run the sample on both a free developer tenant and a paid test tenant. I'm seeing the error page you're seeing when I run it against my free developer tenant, but only when I click on the "Contacts" button. The other operations are working for me on my free developer tenant. Is that what you are seeing, too?

I am not seeing any problem like this on my paid test tenant, so this appears to be a problem with Contacts only, and it appears only on the free developer tenants.

If you used the Visual Studio tools to register your app, you shouldn't have to worry about getting an Azure account or associating it with your O365 tenant. The client that you have already registered should be fine as long as you have assigned the required permissions.

When I run the sample against my free developer tenant and click on the "Contacts" button, my Fiddler trace tells me that the underlying REST call was successful. I see a faulty result set in the response, though. Almost every property value for every contact is either null or empty. The client library seems to be interpreting this as a null result.

The sample code sees that the result set is null and sends you to the misleading error page. This error (for me, at least) has nothing to do with ADAL and/or access tokens. It is simply the result of a null result coming back from the developer tenant.

I made a couple of small changes to the code so that I see an empty result page instead of the error page. From the empty result page, I can add a contact. After I add the contact, I can go to my developer tenant and see that my new contact has been added. But when the sample code tries to retrieve contacts, the result set is null, and I see the empty result page again.

When I try this with a paid O365 test tenant, I am able to see, create, and delete contacts. 

If you see this error page only when you click on the "Contacts" button, then I have duplicated the issue. Can you confirm that this is the problem?
